### ISSUE TITLE
Build failure: requires libc++

### ISSUE THREAD

**Issue by 0-wiz-0** [muja/unrar.rs#65]
I was packaging ouch for pkgsrc and compiling ouch on NetBSD.
The build failed trying to link against `libc++`. NetBSD only provides `libstdc++`.

[In the ouch bugreport](https://github.com/ouch-org/ouch/issues/772) a simple test was suggested to try if the problem is in unrar.rs, and the test seems to indicate that.

I'm not sure what the best fix is.
IIRC, libstdc++ is even automatically linked in when using the `c++` binary to compile code, but I may be mistaken.

**Comment by muja** [comment]
Unfortunately I cannot reproduce this so I won't be able to fix it. Is there a docker image or something similar where the issue can be reproduced?
Otherwise I would suggest "trialing and erroring" with the build flags (which is exactly what I'd do), I personally have no idea which ones are necessary and which ones can be thrown out... the GitHub build matrix will find out any regressions.

**Comment by 0-wiz-0** [comment]
I fixed the build failure (of 'cargo test') on NetBSD with https://github.com/muja/unrar.rs/pull/66
I think the case for OpenBSD is also wrong; FreeBSD might be right or not, I'm not sure.

I get a couple test failures:
```
     Running tests/utf8.rs (target/debug/deps/utf8-14284d5dbd0a3e88)

running 7 tests
test unicode_list ... ok
test unicode_file ... FAILED
test unicode_extract_to ... FAILED
test extract_with_unicode_base ... FAILED
test unicode_entry_extract ... FAILED
test unicode_entry ... ok
test unicode_entry_process_mode ... ok

failures:

---- unicode_file stdout ----
thread 'unicode_file' panicked at tests/utf8.rs:12:84:
called `Result::unwrap()` on an `Err` value: EOpen@Open (Could not open archive)

---- unicode_extract_to stdout ----
thread 'unicode_extract_to' panicked at tests/utf8.rs:23:69:
read failed: Os { code: 2, kind: NotFound, message: "No such file or directory" }

---- extract_with_unicode_base stdout ----
thread 'extract_with_unicode_base' panicked at tests/utf8.rs:40:62:
read failed: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- unicode_entry_extract stdout ----
thread 'unicode_entry_extract' panicked at tests/utf8.rs:67:5:
assertion `left == right` failed
  left: "unicodefilename"
 right: "unicodefilename❤\u{fe0f}.txt"


failures:
    extract_with_unicode_base
    unicode_entry_extract
    unicode_extract_to
    unicode_file

test result: FAILED. 3 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
but it at least gets this far! Before it didn't even link.

**Comment by 0-wiz-0** [comment]
Btw, here is an example if you want to set up a NetBSD runner in github CI:
https://github.com/nih-at/libzip/blob/main/.github/workflows/bsd.yml

**Comment by 0-wiz-0** [comment]
Thank you! Can I please have a new release with the fix included, so I can go back to ouch and let them pull in that version with the fix? :-)

**Comment by muja** [comment]
> Thank you! Can I please have a new release with the fix included, so I can go back to ouch and let them pull in that version with the fix? :-)

Done, 0.5.8 is released

**Comment by 0-wiz-0** [comment]
Thank you!

**Comment by 0-wiz-0** [comment]
While the build of 0.5.8 itself works fine now, when I try using as a dependency, I still get the same link error.
[This commit](https://github.com/muja/unrar.rs/commit/d8de0e466bfa5eb397b8c80731d11bc7918074cb) fixes it, but I guess you might need this on other operating systems and I don't know how to make it conditional. Any ideas?
